FROM scratch

ADD 1e116cfe04ca075c0dad8e622f57b1165f65b274bc9db42762ac6c651961fc25.tar.xz /
ADD 251bfbcb9373ad1d79c9a9e5ebe9bc166310d74cf1b9a7ca6303fadacc8c3f2b.tar.xz /
ADD 3d77883fcd83b72a799c7ba88149b1e1a498ecea40b3b78c15638bb54de564ad.tar.xz /
ADD 662846df166a3b9b4922f7c2a8e57c98e3c21260742de6ffdc20311134973fbd.tar.xz /
ADD 6630a9b4531e7d160291fcc54e50332191d5ba43f784bd0b2fb93cff8b862246.tar.xz /
ADD 713a47ba57be9148d3fccfa7ad8afe987133132189330b193bdcf661e04f5b2e.tar.xz /
ADD 7254e707595aaf8e86dd0e39d6b66cdcf0f8b4abb7d2a996e78334ecaba37b1c.tar.xz /
ADD cc2e895fc928b7ef54b063492fc093280a235c39c5d390f29c3f7622608b90a0.tar.xz /

RUN yum -y groupinstall "Development Tools" && yum -y install openssl openssl-devel libcurl libcurl-devel gcc72 gcc72-c++
RUN curl -O https://cmake.org/files/v3.18/cmake-3.18.0.tar.gz && tar -xvf cmake-3.18.0.tar.gz && cd cmake-3.18.0 && ./bootstrap && make -j6 install && cd .. && rm -rf cmake*
RUN curl -LO https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz && tar -xvf boost_1_77_0.tar.gz && \
    cd boost_1_77_0 && ./bootstrap.sh --with-python=python3 && ./b2 cxxflags="-fPIC" link=static install && cd .. && rm -rf boost*
RUN git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp.git && cd aws-sdk-cpp && mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="s3" -DBUILD_SHARED_LIBS="off" .. && make -j6 install && cd ../.. && rm -rf aws-sdk-cpp
RUN git clone https://github.com/redis/hiredis.git && cd hiredis/ && make install && cd .. && rm -rf hiredis

ENV LANG=en_US.UTF-8
ENV TZ=:/etc/localtime
ENV PATH=/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
ENV LD_LIBRARY_PATH=/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
ENV LAMBDA_TASK_ROOT=/var/task
ENV LAMBDA_RUNTIME_DIR=/var/runtime
