FROM scratch

ADD 01d7e4dfc1ed0bbac9c40a9c5c59173cbd383504baa80f5c02f790a18a8d1f5a.tar.xz /
ADD 04ec01395ff16186f3e716750ddf05152fdcee7f0dc1af75361a5d5ff817e66a.tar.xz /
ADD 5d3671a7ac50c6e6d7cb77294efe7219fdab4912fdf509fede6881afb32c4d3f.tar.xz /
ADD 9882e2c0b9128fab2c7fad5173cc2caf3e61ed106244b79bd055654d4f234afc.tar.xz /
ADD e7f7e7687e6e73fd969387cd25cf9c1884378a17afefe5bcb0d90b4525142cb9.tar.xz /
ADD e8eec162db1f4217a48f45b84e1f30619c1b365107f8fc2ab97d12f067bfdb92.tar.xz /

ENV LANG=en_US.UTF-8
ENV TZ=:/etc/localtime
ENV PATH=/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
ENV LD_LIBRARY_PATH=/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
ENV LAMBDA_TASK_ROOT=/var/task
ENV LAMBDA_RUNTIME_DIR=/var/runtime

RUN yum -y groupinstall "Development Tools" && yum -y install openssl openssl-devel libcurl libcurl-devel gcc72 gcc72-c++ which
RUN curl -O https://cmake.org/files/v3.18/cmake-3.18.0.tar.gz && tar -xvf cmake-3.18.0.tar.gz && cd cmake-3.18.0 && ./bootstrap && make -j6 install && cd .. && rm -rf cmake*
RUN curl -LO https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz && tar -xvf boost_1_77_0.tar.gz && \
    cd boost_1_77_0 && ./bootstrap.sh && ./b2 cxxflags="-fPIC" link=static install && cd .. && rm -rf boost*
RUN git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp.git && cd aws-sdk-cpp && mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_ONLY="s3" -DBUILD_SHARED_LIBS="off" .. && make -j6 install && cd ../.. && rm -rf aws-sdk-cpp
RUN git clone https://github.com/redis/hiredis.git && cd hiredis/ && make install && cd .. && rm -rf hiredis
